"""empty message

Revision ID: f6d4f756d07c
Revises: f68cc6a530d2
Create Date: 2018-12-13 11:52:55.020470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6d4f756d07c'
down_revision = 'f68cc6a530d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('station',
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('postal_code', sa.String(length=9), nullable=True),
    sa.Column('xlocation', sa.String(length=10), nullable=True),
    sa.Column('ylocation', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('station_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('station')
    # ### end Alembic commands ###
